# Generated by Django 4.2.23 on 2025-07-23 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('showroom_agent', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_dimensions', models.JSONField()),
                ('user_preferences', models.JSONField()),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('generated', 'Generated'), ('pending_review', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('ai_reasoning', models.TextField(blank=True)),
                ('dealer_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LayoutTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('room_type', models.CharField(max_length=50)),
                ('style', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='layout_templates/')),
                ('dimensions', models.JSONField()),
                ('product_slots', models.JSONField()),
                ('template_description', models.TextField()),
                ('color_palette', models.JSONField(blank=True, default=list, null=True)),
                ('estimated_budget', models.JSONField(blank=True, default=dict, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('slot_name', models.CharField(max_length=100)),
                ('reasoning', models.TextField(blank=True)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_recommendations', to='design_agent.designrecommendation')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
        migrations.AddField(
            model_name='designrecommendation',
            name='layout_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='design_agent.layouttemplate'),
        ),
        migrations.AddField(
            model_name='designrecommendation',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showroom_agent.usersession'),
        ),
    ]
