# Generated by Django 4.2.23 on 2025-07-04 04:54

from django.db import migrations,models

class Migration(migrations.Migration):

    dependencies = [
        ('design_agent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='layouttemplate',
            name='estimated_budget',
            field=models.JSONField(null=True, blank=True, default=dict)
        ),
    ]
