# Generated by Django 4.2.23 on 2025-07-22 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design_agent', '0002_auto_20250704_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='layouttemplate',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='layout_templates/'),
        ),
    ]
