# Generated by Django 4.2.23 on 2025-07-22 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('design_agent', '0003_layouttemplate_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designrecommendation',
            name='layout_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='design_agent.layouttemplate'),
        ),
    ]
