# Generated by Django 4.2.23 on 2025-07-23 05:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('session_key', models.CharField(default=uuid.uuid4, max_length=100, unique=True)),
                ('preferences', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('room_type', models.CharField(blank=True, choices=[('bathroom', 'Bathroom'), ('kitchen', 'Kitchen'), ('other', 'Other')], max_length=20, null=True)),
                ('style_preference', models.CharField(blank=True, choices=[('modern', 'Modern'), ('traditional', 'Traditional'), ('contemporary', 'Contemporary'), ('rustic', 'Rustic'), ('minimalist', 'Minimalist'), ('industrial', 'Industrial')], max_length=20, null=True)),
                ('budget_range', models.CharField(blank=True, choices=[('low', 'Budget-Friendly'), ('medium', 'Mid-Range'), ('high', 'Premium')], max_length=10, null=True)),
                ('budget_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('room_size', models.CharField(blank=True, choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], max_length=10, null=True)),
                ('total_interactions', models.PositiveIntegerField(default=0)),
                ('completion_percentage', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'showroom_user_sessions',
                'ordering': ['-last_activity'],
            },
        ),
        migrations.CreateModel(
            name='ChatInteraction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_message', models.TextField()),
                ('ai_response', models.TextField()),
                ('intent', models.CharField(choices=[('room_identification', 'Room Identification'), ('style_discussion', 'Style Discussion'), ('pricing_inquiry', 'Pricing Inquiry'), ('product_recommendation', 'Product Recommendation'), ('general_conversation', 'General Conversation')], default='general_conversation', max_length=30)),
                ('extracted_preferences', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='showroom_agent.usersession')),
            ],
            options={
                'db_table': 'showroom_chat_interactions',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['session_key'], name='showroom_us_session_4f32a1_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['is_active', 'created_at'], name='showroom_us_is_acti_5faaa6_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['last_activity'], name='showroom_us_last_ac_d1e089_idx'),
        ),
        migrations.AddIndex(
            model_name='chatinteraction',
            index=models.Index(fields=['session', '-timestamp'], name='showroom_ch_session_72339f_idx'),
        ),
    ]
