# Generated by Django 4.2.23 on 2025-07-22 06:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('showroom_agent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductRecommendation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_id', models.CharField(max_length=50)),
                ('product_name', models.CharField(max_length=200)),
                ('product_category', models.CharField(max_length=100)),
                ('product_style', models.CharField(blank=True, max_length=50)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('relevance_score', models.FloatField()),
                ('recommendation_reason', models.TextField(blank=True)),
                ('was_clicked', models.BooleanField(default=False)),
                ('click_timestamp', models.DateTimeField(blank=True, null=True)),
                ('recommended_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'showroom_product_recommendations',
                'ordering': ['-recommended_at'],
            },
        ),
        migrations.CreateModel(
            name='SessionAnalytics',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('avg_response_time_ms', models.FloatField(default=0)),
                ('total_tokens_used', models.PositiveIntegerField(default=0)),
                ('api_calls_made', models.PositiveIntegerField(default=0)),
                ('session_duration_minutes', models.PositiveIntegerField(default=0)),
                ('messages_sent', models.PositiveIntegerField(default=0)),
                ('recommendations_shown', models.PositiveIntegerField(default=0)),
                ('recommendations_clicked', models.PositiveIntegerField(default=0)),
                ('final_completion_percentage', models.PositiveSmallIntegerField(default=0)),
                ('preferences_collected', models.PositiveSmallIntegerField(default=0)),
                ('conversation_quality_score', models.FloatField(blank=True, null=True)),
                ('user_satisfaction_score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'showroom_session_analytics',
            },
        ),
        migrations.AlterModelOptions(
            name='chatinteraction',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='usersession',
            options={'ordering': ['-last_activity']},
        ),
        migrations.AddField(
            model_name='chatinteraction',
            name='response_time_ms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersession',
            name='completion_percentage',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usersession',
            name='last_activity',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='usersession',
            name='room_size',
            field=models.CharField(blank=True, choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='usersession',
            name='total_interactions',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='chatinteraction',
            name='confidence_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chatinteraction',
            name='extracted_preferences',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='chatinteraction',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='chatinteraction',
            name='intent',
            field=models.CharField(choices=[('room_identification', 'Room Identification'), ('style_discussion', 'Style Discussion'), ('pricing_inquiry', 'Pricing Inquiry'), ('product_recommendation', 'Product Recommendation'), ('general_conversation', 'General Conversation')], default='general_conversation', max_length=30),
        ),
        migrations.AlterField(
            model_name='chatinteraction',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='showroom_agent.usersession'),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='budget_range',
            field=models.CharField(blank=True, choices=[('low', 'Budget-Friendly'), ('medium', 'Mid-Range'), ('high', 'Premium')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='preferences',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='room_type',
            field=models.CharField(blank=True, choices=[('bathroom', 'Bathroom'), ('kitchen', 'Kitchen'), ('other', 'Other')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='session_key',
            field=models.CharField(default=uuid.uuid4, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='style_preference',
            field=models.CharField(blank=True, choices=[('modern', 'Modern'), ('traditional', 'Traditional'), ('contemporary', 'Contemporary'), ('rustic', 'Rustic'), ('minimalist', 'Minimalist'), ('industrial', 'Industrial')], max_length=20, null=True),
        ),
        migrations.AddIndex(
            model_name='chatinteraction',
            index=models.Index(fields=['session', '-timestamp'], name='showroom_ch_session_72339f_idx'),
        ),
        migrations.AddIndex(
            model_name='chatinteraction',
            index=models.Index(fields=['intent', '-timestamp'], name='showroom_ch_intent_73eabe_idx'),
        ),
        migrations.AddIndex(
            model_name='chatinteraction',
            index=models.Index(fields=['-timestamp'], name='showroom_ch_timesta_77cab1_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['session_key'], name='showroom_us_session_4f32a1_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['is_active', 'created_at'], name='showroom_us_is_acti_5faaa6_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['room_type', 'style_preference'], name='showroom_us_room_ty_ff62b3_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['last_activity'], name='showroom_us_last_ac_d1e089_idx'),
        ),
        migrations.AlterModelTable(
            name='chatinteraction',
            table='showroom_chat_interactions',
        ),
        migrations.AlterModelTable(
            name='usersession',
            table='showroom_user_sessions',
        ),
        migrations.AddField(
            model_name='sessionanalytics',
            name='session',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='showroom_agent.usersession'),
        ),
        migrations.AddField(
            model_name='productrecommendation',
            name='interaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='showroom_agent.chatinteraction'),
        ),
        migrations.AddField(
            model_name='productrecommendation',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='showroom_agent.usersession'),
        ),
        migrations.AddIndex(
            model_name='sessionanalytics',
            index=models.Index(fields=['-created_at'], name='showroom_se_created_b32001_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionanalytics',
            index=models.Index(fields=['final_completion_percentage'], name='showroom_se_final_c_13779c_idx'),
        ),
        migrations.AddIndex(
            model_name='productrecommendation',
            index=models.Index(fields=['session', '-recommended_at'], name='showroom_pr_session_49ec7f_idx'),
        ),
        migrations.AddIndex(
            model_name='productrecommendation',
            index=models.Index(fields=['product_id', '-recommended_at'], name='showroom_pr_product_2a3c20_idx'),
        ),
        migrations.AddIndex(
            model_name='productrecommendation',
            index=models.Index(fields=['was_clicked'], name='showroom_pr_was_cli_2aac5d_idx'),
        ),
    ]
