# Generated by Django 4.2.23 on 2025-07-22 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showroom_agent', '0002_productrecommendation_sessionanalytics_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productrecommendation',
            name='interaction',
        ),
        migrations.RemoveField(
            model_name='productrecommendation',
            name='session',
        ),
        migrations.RemoveField(
            model_name='sessionanalytics',
            name='session',
        ),
        migrations.RemoveIndex(
            model_name='chatinteraction',
            name='showroom_ch_intent_73eabe_idx',
        ),
        migrations.RemoveIndex(
            model_name='chatinteraction',
            name='showroom_ch_timesta_77cab1_idx',
        ),
        migrations.RemoveIndex(
            model_name='usersession',
            name='showroom_us_room_ty_ff62b3_idx',
        ),
        migrations.RemoveField(
            model_name='chatinteraction',
            name='confidence_score',
        ),
        migrations.RemoveField(
            model_name='chatinteraction',
            name='response_time_ms',
        ),
        migrations.AddField(
            model_name='usersession',
            name='budget_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.DeleteModel(
            name='ProductRecommendation',
        ),
        migrations.DeleteModel(
            name='SessionAnalytics',
        ),
    ]
