# Generated by Django 4.2.23 on 2025-07-03 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('style', models.CharField(choices=[('modern', 'Modern'), ('traditional', 'Traditional'), ('contemporary', 'Contemporary'), ('rustic', 'Rustic'), ('minimalist', 'Minimalist'), ('industrial', 'Industrial')], max_length=100)),
                ('material', models.CharField(max_length=100)),
                ('finish', models.CharField(max_length=100)),
                ('room_type', models.CharField(choices=[('living_room', 'Living Room'), ('bedroom', 'Bedroom'), ('kitchen', 'Kitchen'), ('dining_room', 'Dining Room'), ('bathroom', 'Bathroom'), ('office', 'Office')], max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_available', models.BooleanField(default=True)),
                ('description', models.TextField()),
                ('specifications', models.JSONField(blank=True, null=True)),
                ('embedding_vector', models.JSONField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productcategory')),
            ],
        ),
    ]
