# Generated by Django 4.2.23 on 2025-07-21 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='room_type',
            field=models.CharField(choices=[('kitchen', 'Kitchen'), ('bathroom', 'Bathroom')], max_length=50),
        ),
    ]
